spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/railway-ticket_reservation-system
    password: dhaaneshwar@13
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

twilio:
  account_sid: AC53fd6e2045febb3bc221417f9652a642
  auth_token: 677d11ef84950dbf3bf6b9a8a6a69977
  trial_number: +19895107622

